(function() {var implementors = {};
implementors["serde"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='serde/de/value/enum.Error.html' title='serde::de::value::Error'>Error</a>",];implementors["objc"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='objc/struct.MessageError.html' title='objc::MessageError'>MessageError</a>",];implementors["gleam"] = [];implementors["shared_library"] = [];implementors["core_foundation"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='core_foundation/error/struct.CFError.html' title='core_foundation::error::CFError'>CFError</a>",];implementors["core_graphics"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='core_foundation/error/struct.CFError.html' title='core_foundation::error::CFError'>CFError</a>",];implementors["cocoa"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='objc/message/struct.MessageError.html' title='objc::message::MessageError'>MessageError</a>",];implementors["glutin"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='glutin/enum.CreationError.html' title='glutin::CreationError'>CreationError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='glutin/enum.ContextError.html' title='glutin::ContextError'>ContextError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
